### ISSUE TITLE
PATH+=: is a bashism

### ISSUE THREAD

**Issue by Jookia** [edward-riley/Glok#4]
So this is a super weird bug since I don't actually use the software. I just saw in the README that you recommend setting PATH like 'export PATH+=/foo' which I've never seen before. I tried it in my shell (zsh) and it didn't work, but in Bash it works:

```
jookia@novena-choice-citizen:~% bash
jookia@novena-choice-citizen:~$ export PATH+=/foo
jookia@novena-choice-citizen:~$ zsh
jookia@novena-choice-citizen:~% export PATH+=/foo
export: not valid in this context: PATH+
jookia@novena-choice-citizen:~% dash
$ export PATH+=/foo
dash: 1: export: PATH+: bad variable name
```

It might be worth just using the regular 'export PATH=$PATH:/foo'

**Comment by edward-riley** [comment]
should be fixed now. Thank you for your help
